# Generated by Django 2.2.10 on 2020-04-22 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parallel', models.IntegerField(verbose_name='номер параллели')),
                ('letter', models.CharField(max_length=1, verbose_name='буква класса')),
            ],
            options={
                'verbose_name': 'класс',
                'verbose_name_plural': 'классы',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='название предмета')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.Class', verbose_name='класс, которому преподаётся данный предмет')),
            ],
            options={
                'verbose_name': 'предмет',
                'verbose_name_plural': 'предметы',
            },
        ),
    ]
